version: 2
updates:
  - package-ecosystem: pip
    directory: /healer
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /dashboard
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: docker
    directory: /healer
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /dashboard
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /demo_services/leaky_service
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /demo_services/flaky_service
    schedule:
      interval: weekly
  - package-ecosystem: docker-compose
    directory: /infra
    schedule:
      interval: weekly
